%% Intra-family environ dependencies among Mizar YELLOW* and WAYBEL* articles.
%% Source: ../MML/mml. Edge A --> B means A depends on B.
%% Node order in this file is least-dependent → most-dependent.
flowchart TB
  YELLOW_0[YELLOW_0]:::yellow
  YELLOW18[YELLOW18]:::yellow
  WAYBEL_0[WAYBEL_0]:::waybel
  YELLOW_1[YELLOW_1]:::yellow
  YELLOW20[YELLOW20]:::yellow
  YELLOW_2[YELLOW_2]:::yellow
  WAYBEL_1[WAYBEL_1]:::waybel
  YELLOW_3[YELLOW_3]:::yellow
  YELLOW_4[YELLOW_4]:::yellow
  YELLOW_5[YELLOW_5]:::yellow
  WAYBEL_2[WAYBEL_2]:::waybel
  YELLOW11[YELLOW11]:::yellow
  WAYBEL_3[WAYBEL_3]:::waybel
  WAYBEL_4[WAYBEL_4]:::waybel
  YELLOW_6[YELLOW_6]:::yellow
  YELLOW_8[YELLOW_8]:::yellow
  WAYBEL_5[WAYBEL_5]:::waybel
  WAYBEL35[WAYBEL35]:::waybel
  YELLOW_7[YELLOW_7]:::yellow
  WAYBEL10[WAYBEL10]:::waybel
  WAYBEL_6[WAYBEL_6]:::waybel
  WAYBEL_7[WAYBEL_7]:::waybel
  WAYBEL_8[WAYBEL_8]:::waybel
  WAYBEL12[WAYBEL12]:::waybel
  WAYBEL_9[WAYBEL_9]:::waybel
  WAYBEL11[WAYBEL11]:::waybel
  WAYBEL13[WAYBEL13]:::waybel
  YELLOW_9[YELLOW_9]:::yellow
  YELLOW12[YELLOW12]:::yellow
  WAYBEL14[WAYBEL14]:::waybel
  YELLOW10[YELLOW10]:::yellow
  WAYBEL17[WAYBEL17]:::waybel
  WAYBEL15[WAYBEL15]:::waybel
  YELLOW13[YELLOW13]:::yellow
  WAYBEL16[WAYBEL16]:::waybel
  WAYBEL19[WAYBEL19]:::waybel
  WAYBEL18[WAYBEL18]:::waybel
  YELLOW17[YELLOW17]:::yellow
  WAYBEL24[WAYBEL24]:::waybel
  WAYBEL20[WAYBEL20]:::waybel
  WAYBEL22[WAYBEL22]:::waybel
  YELLOW14[YELLOW14]:::yellow
  WAYBEL21[WAYBEL21]:::waybel
  WAYBEL23[WAYBEL23]:::waybel
  WAYBEL28[WAYBEL28]:::waybel
  YELLOW15[YELLOW15]:::yellow
  WAYBEL25[WAYBEL25]:::waybel
  YELLOW16[YELLOW16]:::yellow
  WAYBEL26[WAYBEL26]:::waybel
  WAYBEL27[WAYBEL27]:::waybel
  YELLOW21[YELLOW21]:::yellow
  WAYBEL29[WAYBEL29]:::waybel
  WAYBEL32[WAYBEL32]:::waybel
  WAYBEL34[WAYBEL34]:::waybel
  YELLOW19[YELLOW19]:::yellow
  WAYBEL30[WAYBEL30]:::waybel
  WAYBEL31[WAYBEL31]:::waybel
  WAYBEL33[WAYBEL33]:::waybel
  WAYBEL_0 --> YELLOW_0
  YELLOW_1 --> YELLOW_0
  YELLOW20 --> YELLOW18
  YELLOW_2 --> YELLOW_0
  YELLOW_2 --> WAYBEL_0
  YELLOW_2 --> YELLOW_1
  WAYBEL_1 --> YELLOW_0
  WAYBEL_1 --> WAYBEL_0
  WAYBEL_1 --> YELLOW_1
  WAYBEL_1 --> YELLOW_2
  YELLOW_3 --> YELLOW_0
  YELLOW_3 --> WAYBEL_0
  YELLOW_3 --> YELLOW_2
  YELLOW_4 --> YELLOW_0
  YELLOW_4 --> WAYBEL_0
  YELLOW_4 --> YELLOW_1
  YELLOW_4 --> YELLOW_2
  YELLOW_4 --> YELLOW_3
  YELLOW_5 --> YELLOW_0
  YELLOW_5 --> WAYBEL_0
  YELLOW_5 --> WAYBEL_1
  WAYBEL_2 --> YELLOW_0
  WAYBEL_2 --> WAYBEL_0
  WAYBEL_2 --> YELLOW_1
  WAYBEL_2 --> YELLOW_2
  WAYBEL_2 --> WAYBEL_1
  WAYBEL_2 --> YELLOW_3
  WAYBEL_2 --> YELLOW_4
  YELLOW11 --> YELLOW_0
  YELLOW11 --> WAYBEL_0
  YELLOW11 --> YELLOW_1
  YELLOW11 --> WAYBEL_1
  YELLOW11 --> YELLOW_3
  YELLOW11 --> YELLOW_5
  WAYBEL_3 --> YELLOW_0
  WAYBEL_3 --> WAYBEL_0
  WAYBEL_3 --> YELLOW_1
  WAYBEL_3 --> YELLOW_2
  WAYBEL_3 --> YELLOW_4
  WAYBEL_3 --> WAYBEL_2
  WAYBEL_4 --> YELLOW_0
  WAYBEL_4 --> WAYBEL_0
  WAYBEL_4 --> YELLOW_1
  WAYBEL_4 --> YELLOW_2
  WAYBEL_4 --> WAYBEL_1
  WAYBEL_4 --> YELLOW_4
  WAYBEL_4 --> WAYBEL_2
  WAYBEL_4 --> WAYBEL_3
  YELLOW_6 --> YELLOW_0
  YELLOW_6 --> WAYBEL_0
  YELLOW_6 --> YELLOW_1
  YELLOW_6 --> YELLOW_3
  YELLOW_6 --> WAYBEL_3
  YELLOW_8 --> WAYBEL_3
  WAYBEL_5 --> YELLOW_0
  WAYBEL_5 --> WAYBEL_0
  WAYBEL_5 --> YELLOW_1
  WAYBEL_5 --> YELLOW_2
  WAYBEL_5 --> WAYBEL_1
  WAYBEL_5 --> WAYBEL_3
  WAYBEL_5 --> YELLOW_6
  WAYBEL35 --> YELLOW_0
  WAYBEL35 --> WAYBEL_0
  WAYBEL35 --> YELLOW_1
  WAYBEL35 --> YELLOW_2
  WAYBEL35 --> WAYBEL_1
  WAYBEL35 --> YELLOW_4
  WAYBEL35 --> WAYBEL_4
  YELLOW_7 --> YELLOW_0
  YELLOW_7 --> WAYBEL_0
  YELLOW_7 --> YELLOW_2
  YELLOW_7 --> WAYBEL_1
  YELLOW_7 --> YELLOW_5
  YELLOW_7 --> WAYBEL_5
  WAYBEL10 --> YELLOW_0
  WAYBEL10 --> WAYBEL_0
  WAYBEL10 --> YELLOW_1
  WAYBEL10 --> YELLOW_2
  WAYBEL10 --> WAYBEL_1
  WAYBEL10 --> WAYBEL_3
  WAYBEL10 --> YELLOW_7
  WAYBEL_6 --> YELLOW_0
  WAYBEL_6 --> WAYBEL_0
  WAYBEL_6 --> YELLOW_1
  WAYBEL_6 --> YELLOW_2
  WAYBEL_6 --> WAYBEL_1
  WAYBEL_6 --> YELLOW_3
  WAYBEL_6 --> YELLOW_4
  WAYBEL_6 --> YELLOW_5
  WAYBEL_6 --> WAYBEL_2
  WAYBEL_6 --> WAYBEL_3
  WAYBEL_6 --> WAYBEL_4
  WAYBEL_6 --> YELLOW_8
  WAYBEL_6 --> WAYBEL_5
  WAYBEL_6 --> YELLOW_7
  WAYBEL_7 --> YELLOW_0
  WAYBEL_7 --> WAYBEL_0
  WAYBEL_7 --> YELLOW_1
  WAYBEL_7 --> YELLOW_2
  WAYBEL_7 --> WAYBEL_1
  WAYBEL_7 --> YELLOW_3
  WAYBEL_7 --> YELLOW_4
  WAYBEL_7 --> YELLOW_5
  WAYBEL_7 --> WAYBEL_3
  WAYBEL_7 --> WAYBEL_4
  WAYBEL_7 --> WAYBEL_5
  WAYBEL_7 --> YELLOW_7
  WAYBEL_7 --> WAYBEL_6
  WAYBEL_8 --> YELLOW_0
  WAYBEL_8 --> WAYBEL_0
  WAYBEL_8 --> YELLOW_1
  WAYBEL_8 --> YELLOW_2
  WAYBEL_8 --> WAYBEL_1
  WAYBEL_8 --> YELLOW_3
  WAYBEL_8 --> YELLOW_5
  WAYBEL_8 --> WAYBEL_2
  WAYBEL_8 --> WAYBEL_3
  WAYBEL_8 --> WAYBEL_4
  WAYBEL_8 --> YELLOW_7
  WAYBEL_8 --> WAYBEL_6
  WAYBEL_8 --> WAYBEL_7
  WAYBEL12 --> YELLOW_0
  WAYBEL12 --> WAYBEL_0
  WAYBEL12 --> YELLOW_1
  WAYBEL12 --> YELLOW_2
  WAYBEL12 --> WAYBEL_1
  WAYBEL12 --> YELLOW_3
  WAYBEL12 --> YELLOW_4
  WAYBEL12 --> WAYBEL_3
  WAYBEL12 --> WAYBEL_4
  WAYBEL12 --> YELLOW_6
  WAYBEL12 --> YELLOW_8
  WAYBEL12 --> WAYBEL_6
  WAYBEL12 --> WAYBEL_7
  WAYBEL_9 --> YELLOW_0
  WAYBEL_9 --> WAYBEL_0
  WAYBEL_9 --> YELLOW_1
  WAYBEL_9 --> YELLOW_2
  WAYBEL_9 --> WAYBEL_1
  WAYBEL_9 --> YELLOW_4
  WAYBEL_9 --> WAYBEL_2
  WAYBEL_9 --> WAYBEL_3
  WAYBEL_9 --> YELLOW_6
  WAYBEL_9 --> YELLOW_7
  WAYBEL_9 --> WAYBEL_7
  WAYBEL_9 --> WAYBEL_8
  WAYBEL11 --> YELLOW_0
  WAYBEL11 --> WAYBEL_0
  WAYBEL11 --> YELLOW_1
  WAYBEL11 --> YELLOW_2
  WAYBEL11 --> WAYBEL_1
  WAYBEL11 --> YELLOW_3
  WAYBEL11 --> YELLOW_4
  WAYBEL11 --> WAYBEL_2
  WAYBEL11 --> WAYBEL_3
  WAYBEL11 --> WAYBEL_4
  WAYBEL11 --> YELLOW_6
  WAYBEL11 --> YELLOW_8
  WAYBEL11 --> WAYBEL_5
  WAYBEL11 --> YELLOW_7
  WAYBEL11 --> WAYBEL_6
  WAYBEL11 --> WAYBEL_7
  WAYBEL11 --> WAYBEL_9
  WAYBEL13 --> YELLOW_0
  WAYBEL13 --> WAYBEL_0
  WAYBEL13 --> YELLOW_1
  WAYBEL13 --> YELLOW_2
  WAYBEL13 --> WAYBEL_1
  WAYBEL13 --> WAYBEL_3
  WAYBEL13 --> WAYBEL_4
  WAYBEL13 --> WAYBEL_5
  WAYBEL13 --> WAYBEL10
  WAYBEL13 --> WAYBEL_8
  YELLOW_9 --> YELLOW_0
  YELLOW_9 --> WAYBEL_0
  YELLOW_9 --> YELLOW_2
  YELLOW_9 --> WAYBEL_1
  YELLOW_9 --> YELLOW_6
  YELLOW_9 --> YELLOW_8
  YELLOW_9 --> YELLOW_7
  YELLOW_9 --> WAYBEL_9
  YELLOW_9 --> WAYBEL11
  YELLOW12 --> YELLOW_0
  YELLOW12 --> WAYBEL_0
  YELLOW12 --> YELLOW_2
  YELLOW12 --> WAYBEL_1
  YELLOW12 --> YELLOW_3
  YELLOW12 --> YELLOW_4
  YELLOW12 --> WAYBEL_2
  YELLOW12 --> WAYBEL_3
  YELLOW12 --> YELLOW_8
  YELLOW12 --> YELLOW_7
  YELLOW12 --> WAYBEL_8
  YELLOW12 --> WAYBEL11
  YELLOW12 --> YELLOW_9
  WAYBEL14 --> YELLOW_0
  WAYBEL14 --> WAYBEL_0
  WAYBEL14 --> YELLOW_1
  WAYBEL14 --> YELLOW_2
  WAYBEL14 --> WAYBEL_1
  WAYBEL14 --> YELLOW_3
  WAYBEL14 --> YELLOW_4
  WAYBEL14 --> WAYBEL_2
  WAYBEL14 --> WAYBEL_3
  WAYBEL14 --> WAYBEL_4
  WAYBEL14 --> YELLOW_6
  WAYBEL14 --> YELLOW_8
  WAYBEL14 --> WAYBEL_5
  WAYBEL14 --> YELLOW_7
  WAYBEL14 --> WAYBEL_6
  WAYBEL14 --> WAYBEL_8
  WAYBEL14 --> WAYBEL12
  WAYBEL14 --> WAYBEL_9
  WAYBEL14 --> WAYBEL11
  YELLOW10 --> YELLOW_0
  YELLOW10 --> WAYBEL_0
  YELLOW10 --> WAYBEL_1
  YELLOW10 --> YELLOW_3
  YELLOW10 --> YELLOW_4
  YELLOW10 --> WAYBEL_2
  YELLOW10 --> WAYBEL_3
  YELLOW10 --> WAYBEL_6
  YELLOW10 --> WAYBEL_8
  YELLOW10 --> WAYBEL11
  YELLOW10 --> WAYBEL14
  WAYBEL17 --> YELLOW_0
  WAYBEL17 --> WAYBEL_0
  WAYBEL17 --> YELLOW_1
  WAYBEL17 --> YELLOW_2
  WAYBEL17 --> WAYBEL_1
  WAYBEL17 --> WAYBEL_2
  WAYBEL17 --> WAYBEL_3
  WAYBEL17 --> WAYBEL_4
  WAYBEL17 --> YELLOW_8
  WAYBEL17 --> WAYBEL10
  WAYBEL17 --> WAYBEL_8
  WAYBEL17 --> WAYBEL_9
  WAYBEL17 --> WAYBEL11
  WAYBEL17 --> WAYBEL13
  WAYBEL15 --> YELLOW_0
  WAYBEL15 --> WAYBEL_0
  WAYBEL15 --> YELLOW_1
  WAYBEL15 --> YELLOW_2
  WAYBEL15 --> WAYBEL_1
  WAYBEL15 --> YELLOW_5
  WAYBEL15 --> WAYBEL_2
  WAYBEL15 --> WAYBEL_3
  WAYBEL15 --> YELLOW_6
  WAYBEL15 --> WAYBEL_5
  WAYBEL15 --> YELLOW_7
  WAYBEL15 --> WAYBEL10
  WAYBEL15 --> WAYBEL_6
  WAYBEL15 --> WAYBEL_8
  WAYBEL15 --> WAYBEL13
  WAYBEL15 --> WAYBEL14
  YELLOW13 --> YELLOW_0
  YELLOW13 --> WAYBEL_0
  YELLOW13 --> YELLOW_1
  YELLOW13 --> YELLOW_2
  YELLOW13 --> WAYBEL_1
  YELLOW13 --> YELLOW_3
  YELLOW13 --> YELLOW_4
  YELLOW13 --> WAYBEL_2
  YELLOW13 --> YELLOW11
  YELLOW13 --> WAYBEL_3
  YELLOW13 --> YELLOW_8
  YELLOW13 --> WAYBEL_9
  YELLOW13 --> YELLOW_9
  YELLOW13 --> YELLOW12
  YELLOW13 --> WAYBEL14
  WAYBEL16 --> YELLOW_0
  WAYBEL16 --> WAYBEL_0
  WAYBEL16 --> YELLOW_1
  WAYBEL16 --> YELLOW_2
  WAYBEL16 --> WAYBEL_1
  WAYBEL16 --> YELLOW_4
  WAYBEL16 --> WAYBEL_2
  WAYBEL16 --> WAYBEL_3
  WAYBEL16 --> WAYBEL_4
  WAYBEL16 --> YELLOW_8
  WAYBEL16 --> YELLOW_7
  WAYBEL16 --> WAYBEL_6
  WAYBEL16 --> WAYBEL_7
  WAYBEL16 --> WAYBEL_8
  WAYBEL16 --> WAYBEL13
  WAYBEL16 --> WAYBEL14
  WAYBEL16 --> WAYBEL15
  WAYBEL19 --> YELLOW_0
  WAYBEL19 --> WAYBEL_0
  WAYBEL19 --> YELLOW_1
  WAYBEL19 --> YELLOW_2
  WAYBEL19 --> WAYBEL_1
  WAYBEL19 --> YELLOW_3
  WAYBEL19 --> YELLOW_5
  WAYBEL19 --> WAYBEL_2
  WAYBEL19 --> WAYBEL_3
  WAYBEL19 --> YELLOW_6
  WAYBEL19 --> YELLOW_8
  WAYBEL19 --> YELLOW_7
  WAYBEL19 --> WAYBEL_7
  WAYBEL19 --> WAYBEL_9
  WAYBEL19 --> WAYBEL11
  WAYBEL19 --> YELLOW_9
  WAYBEL19 --> YELLOW12
  WAYBEL19 --> WAYBEL14
  WAYBEL19 --> YELLOW10
  WAYBEL18 --> YELLOW_0
  WAYBEL18 --> WAYBEL_0
  WAYBEL18 --> YELLOW_1
  WAYBEL18 --> WAYBEL_1
  WAYBEL18 --> WAYBEL_3
  WAYBEL18 --> WAYBEL_5
  WAYBEL18 --> WAYBEL_7
  WAYBEL18 --> WAYBEL_8
  WAYBEL18 --> WAYBEL_9
  WAYBEL18 --> WAYBEL11
  WAYBEL18 --> WAYBEL13
  WAYBEL18 --> YELLOW_9
  WAYBEL18 --> WAYBEL14
  WAYBEL18 --> WAYBEL17
  YELLOW17 --> YELLOW_1
  YELLOW17 --> WAYBEL_3
  YELLOW17 --> YELLOW_6
  YELLOW17 --> WAYBEL_7
  YELLOW17 --> WAYBEL18
  WAYBEL24 --> YELLOW_0
  WAYBEL24 --> WAYBEL_0
  WAYBEL24 --> YELLOW_1
  WAYBEL24 --> YELLOW_2
  WAYBEL24 --> WAYBEL_1
  WAYBEL24 --> YELLOW_3
  WAYBEL24 --> YELLOW_5
  WAYBEL24 --> WAYBEL_3
  WAYBEL24 --> WAYBEL10
  WAYBEL24 --> WAYBEL_9
  WAYBEL24 --> WAYBEL11
  WAYBEL24 --> YELLOW10
  WAYBEL24 --> WAYBEL17
  WAYBEL24 --> WAYBEL15
  WAYBEL20 --> YELLOW_0
  WAYBEL20 --> WAYBEL_0
  WAYBEL20 --> YELLOW_1
  WAYBEL20 --> YELLOW_2
  WAYBEL20 --> WAYBEL_1
  WAYBEL20 --> YELLOW_3
  WAYBEL20 --> WAYBEL_3
  WAYBEL20 --> WAYBEL_5
  WAYBEL20 --> WAYBEL10
  WAYBEL20 --> WAYBEL13
  WAYBEL20 --> YELLOW_9
  WAYBEL20 --> YELLOW10
  WAYBEL20 --> WAYBEL17
  WAYBEL20 --> WAYBEL15
  WAYBEL20 --> WAYBEL16
  WAYBEL22 --> YELLOW_0
  WAYBEL22 --> WAYBEL_0
  WAYBEL22 --> YELLOW_1
  WAYBEL22 --> YELLOW_2
  WAYBEL22 --> WAYBEL_1
  WAYBEL22 --> YELLOW_3
  WAYBEL22 --> WAYBEL_3
  WAYBEL22 --> WAYBEL_4
  WAYBEL22 --> WAYBEL_5
  WAYBEL22 --> YELLOW_7
  WAYBEL22 --> WAYBEL_8
  WAYBEL22 --> WAYBEL11
  WAYBEL22 --> WAYBEL13
  WAYBEL22 --> WAYBEL14
  WAYBEL22 --> WAYBEL17
  WAYBEL22 --> WAYBEL15
  WAYBEL22 --> WAYBEL16
  WAYBEL22 --> WAYBEL20
  YELLOW14 --> YELLOW_0
  YELLOW14 --> WAYBEL_0
  YELLOW14 --> YELLOW_1
  YELLOW14 --> YELLOW_2
  YELLOW14 --> WAYBEL_1
  YELLOW14 --> WAYBEL_3
  YELLOW14 --> YELLOW_6
  YELLOW14 --> YELLOW_8
  YELLOW14 --> WAYBEL10
  YELLOW14 --> WAYBEL_9
  YELLOW14 --> WAYBEL11
  YELLOW14 --> WAYBEL13
  YELLOW14 --> YELLOW_9
  YELLOW14 --> YELLOW12
  YELLOW14 --> WAYBEL19
  YELLOW14 --> WAYBEL18
  YELLOW14 --> WAYBEL24
  WAYBEL21 --> YELLOW_0
  WAYBEL21 --> WAYBEL_0
  WAYBEL21 --> YELLOW_2
  WAYBEL21 --> WAYBEL_1
  WAYBEL21 --> YELLOW_4
  WAYBEL21 --> WAYBEL_2
  WAYBEL21 --> WAYBEL_3
  WAYBEL21 --> YELLOW_6
  WAYBEL21 --> WAYBEL_5
  WAYBEL21 --> YELLOW_7
  WAYBEL21 --> WAYBEL10
  WAYBEL21 --> WAYBEL_6
  WAYBEL21 --> WAYBEL_9
  WAYBEL21 --> WAYBEL11
  WAYBEL21 --> YELLOW_9
  WAYBEL21 --> WAYBEL17
  WAYBEL21 --> WAYBEL19
  WAYBEL21 --> WAYBEL20
  WAYBEL23 --> YELLOW_0
  WAYBEL23 --> WAYBEL_0
  WAYBEL23 --> YELLOW_1
  WAYBEL23 --> YELLOW_2
  WAYBEL23 --> WAYBEL_1
  WAYBEL23 --> YELLOW_3
  WAYBEL23 --> YELLOW_5
  WAYBEL23 --> WAYBEL_3
  WAYBEL23 --> WAYBEL10
  WAYBEL23 --> WAYBEL_7
  WAYBEL23 --> WAYBEL_8
  WAYBEL23 --> WAYBEL13
  WAYBEL23 --> YELLOW12
  WAYBEL23 --> WAYBEL14
  WAYBEL23 --> WAYBEL20
  WAYBEL23 --> WAYBEL21
  WAYBEL28 --> YELLOW_0
  WAYBEL28 --> WAYBEL_0
  WAYBEL28 --> YELLOW_2
  WAYBEL28 --> YELLOW_4
  WAYBEL28 --> WAYBEL_3
  WAYBEL28 --> YELLOW_6
  WAYBEL28 --> WAYBEL_8
  WAYBEL28 --> WAYBEL_9
  WAYBEL28 --> WAYBEL11
  WAYBEL28 --> YELLOW_9
  WAYBEL28 --> YELLOW12
  WAYBEL28 --> WAYBEL17
  WAYBEL28 --> WAYBEL21
  YELLOW15 --> YELLOW_0
  YELLOW15 --> WAYBEL_0
  YELLOW15 --> WAYBEL_3
  YELLOW15 --> YELLOW_8
  YELLOW15 --> WAYBEL_8
  YELLOW15 --> YELLOW_9
  YELLOW15 --> WAYBEL23
  WAYBEL25 --> YELLOW_0
  WAYBEL25 --> WAYBEL_0
  WAYBEL25 --> YELLOW_1
  WAYBEL25 --> YELLOW_2
  WAYBEL25 --> WAYBEL_1
  WAYBEL25 --> YELLOW_4
  WAYBEL25 --> WAYBEL_2
  WAYBEL25 --> WAYBEL_3
  WAYBEL25 --> YELLOW_6
  WAYBEL25 --> YELLOW_8
  WAYBEL25 --> WAYBEL10
  WAYBEL25 --> WAYBEL_7
  WAYBEL25 --> WAYBEL_8
  WAYBEL25 --> WAYBEL_9
  WAYBEL25 --> WAYBEL11
  WAYBEL25 --> WAYBEL13
  WAYBEL25 --> YELLOW_9
  WAYBEL25 --> YELLOW12
  WAYBEL25 --> WAYBEL14
  WAYBEL25 --> WAYBEL17
  WAYBEL25 --> WAYBEL15
  WAYBEL25 --> WAYBEL19
  WAYBEL25 --> WAYBEL18
  WAYBEL25 --> WAYBEL24
  WAYBEL25 --> WAYBEL20
  WAYBEL25 --> YELLOW14
  WAYBEL25 --> WAYBEL21
  YELLOW16 --> YELLOW_0
  YELLOW16 --> WAYBEL_0
  YELLOW16 --> YELLOW_1
  YELLOW16 --> YELLOW_2
  YELLOW16 --> WAYBEL_1
  YELLOW16 --> WAYBEL_3
  YELLOW16 --> YELLOW_6
  YELLOW16 --> WAYBEL10
  YELLOW16 --> WAYBEL13
  YELLOW16 --> YELLOW_9
  YELLOW16 --> YELLOW12
  YELLOW16 --> WAYBEL17
  YELLOW16 --> WAYBEL15
  YELLOW16 --> WAYBEL18
  YELLOW16 --> WAYBEL20
  YELLOW16 --> WAYBEL21
  YELLOW16 --> WAYBEL25
  WAYBEL26 --> YELLOW_0
  WAYBEL26 --> WAYBEL_0
  WAYBEL26 --> YELLOW_1
  WAYBEL26 --> YELLOW_2
  WAYBEL26 --> WAYBEL_1
  WAYBEL26 --> WAYBEL_2
  WAYBEL26 --> WAYBEL_3
  WAYBEL26 --> YELLOW_6
  WAYBEL26 --> WAYBEL10
  WAYBEL26 --> WAYBEL_9
  WAYBEL26 --> WAYBEL11
  WAYBEL26 --> YELLOW_9
  WAYBEL26 --> YELLOW12
  WAYBEL26 --> WAYBEL14
  WAYBEL26 --> WAYBEL17
  WAYBEL26 --> WAYBEL15
  WAYBEL26 --> WAYBEL18
  WAYBEL26 --> WAYBEL24
  WAYBEL26 --> WAYBEL20
  WAYBEL26 --> YELLOW14
  WAYBEL26 --> WAYBEL21
  WAYBEL26 --> WAYBEL25
  WAYBEL26 --> YELLOW16
  WAYBEL27 --> YELLOW_0
  WAYBEL27 --> WAYBEL_0
  WAYBEL27 --> YELLOW_1
  WAYBEL27 --> YELLOW_2
  WAYBEL27 --> WAYBEL_1
  WAYBEL27 --> YELLOW_3
  WAYBEL27 --> WAYBEL_2
  WAYBEL27 --> WAYBEL_3
  WAYBEL27 --> WAYBEL10
  WAYBEL27 --> WAYBEL_6
  WAYBEL27 --> WAYBEL_8
  WAYBEL27 --> WAYBEL_9
  WAYBEL27 --> WAYBEL11
  WAYBEL27 --> WAYBEL13
  WAYBEL27 --> YELLOW_9
  WAYBEL27 --> WAYBEL14
  WAYBEL27 --> WAYBEL17
  WAYBEL27 --> WAYBEL15
  WAYBEL27 --> WAYBEL19
  WAYBEL27 --> WAYBEL18
  WAYBEL27 --> WAYBEL24
  WAYBEL27 --> WAYBEL20
  WAYBEL27 --> YELLOW14
  WAYBEL27 --> WAYBEL21
  WAYBEL27 --> WAYBEL25
  WAYBEL27 --> YELLOW16
  WAYBEL27 --> WAYBEL26
  YELLOW21 --> YELLOW_0
  YELLOW21 --> YELLOW18
  YELLOW21 --> WAYBEL_0
  YELLOW21 --> YELLOW_1
  YELLOW21 --> YELLOW20
  YELLOW21 --> YELLOW_2
  YELLOW21 --> WAYBEL_3
  YELLOW21 --> WAYBEL10
  YELLOW21 --> WAYBEL_8
  YELLOW21 --> WAYBEL13
  YELLOW21 --> YELLOW_9
  YELLOW21 --> WAYBEL17
  YELLOW21 --> WAYBEL20
  YELLOW21 --> YELLOW16
  WAYBEL29 --> YELLOW_0
  WAYBEL29 --> WAYBEL_0
  WAYBEL29 --> YELLOW_1
  WAYBEL29 --> YELLOW_2
  WAYBEL29 --> WAYBEL_1
  WAYBEL29 --> YELLOW_3
  WAYBEL29 --> WAYBEL_3
  WAYBEL29 --> YELLOW_6
  WAYBEL29 --> WAYBEL_5
  WAYBEL29 --> WAYBEL10
  WAYBEL29 --> WAYBEL_8
  WAYBEL29 --> WAYBEL_9
  WAYBEL29 --> WAYBEL11
  WAYBEL29 --> WAYBEL13
  WAYBEL29 --> YELLOW_9
  WAYBEL29 --> YELLOW12
  WAYBEL29 --> WAYBEL14
  WAYBEL29 --> WAYBEL17
  WAYBEL29 --> WAYBEL15
  WAYBEL29 --> WAYBEL19
  WAYBEL29 --> WAYBEL18
  WAYBEL29 --> WAYBEL24
  WAYBEL29 --> WAYBEL20
  WAYBEL29 --> YELLOW14
  WAYBEL29 --> WAYBEL21
  WAYBEL29 --> WAYBEL25
  WAYBEL29 --> YELLOW16
  WAYBEL29 --> WAYBEL26
  WAYBEL29 --> WAYBEL27
  WAYBEL32 --> YELLOW_0
  WAYBEL32 --> WAYBEL_0
  WAYBEL32 --> YELLOW_2
  WAYBEL32 --> WAYBEL_1
  WAYBEL32 --> WAYBEL_2
  WAYBEL32 --> WAYBEL_3
  WAYBEL32 --> YELLOW_6
  WAYBEL32 --> YELLOW_8
  WAYBEL32 --> WAYBEL_7
  WAYBEL32 --> WAYBEL_8
  WAYBEL32 --> WAYBEL_9
  WAYBEL32 --> WAYBEL11
  WAYBEL32 --> YELLOW_9
  WAYBEL32 --> WAYBEL19
  WAYBEL32 --> YELLOW14
  WAYBEL32 --> WAYBEL21
  WAYBEL32 --> WAYBEL29
  WAYBEL34 --> YELLOW_0
  WAYBEL34 --> YELLOW18
  WAYBEL34 --> WAYBEL_0
  WAYBEL34 --> YELLOW20
  WAYBEL34 --> YELLOW_2
  WAYBEL34 --> WAYBEL_1
  WAYBEL34 --> YELLOW_3
  WAYBEL34 --> WAYBEL_2
  WAYBEL34 --> WAYBEL_3
  WAYBEL34 --> YELLOW_7
  WAYBEL34 --> WAYBEL10
  WAYBEL34 --> WAYBEL_6
  WAYBEL34 --> WAYBEL_8
  WAYBEL34 --> WAYBEL_9
  WAYBEL34 --> WAYBEL11
  WAYBEL34 --> YELLOW_9
  WAYBEL34 --> WAYBEL17
  WAYBEL34 --> WAYBEL15
  WAYBEL34 --> WAYBEL18
  WAYBEL34 --> WAYBEL20
  WAYBEL34 --> WAYBEL21
  WAYBEL34 --> YELLOW21
  YELLOW19 --> YELLOW_0
  YELLOW19 --> WAYBEL_0
  YELLOW19 --> YELLOW_1
  YELLOW19 --> WAYBEL_1
  YELLOW19 --> YELLOW_5
  YELLOW19 --> YELLOW_6
  YELLOW19 --> YELLOW_7
  YELLOW19 --> WAYBEL_7
  YELLOW19 --> WAYBEL_8
  YELLOW19 --> WAYBEL12
  YELLOW19 --> WAYBEL_9
  YELLOW19 --> WAYBEL21
  YELLOW19 --> WAYBEL32
  WAYBEL30 --> YELLOW_0
  WAYBEL30 --> WAYBEL_0
  WAYBEL30 --> YELLOW_1
  WAYBEL30 --> YELLOW_2
  WAYBEL30 --> WAYBEL_1
  WAYBEL30 --> YELLOW_3
  WAYBEL30 --> YELLOW_4
  WAYBEL30 --> WAYBEL_2
  WAYBEL30 --> WAYBEL_3
  WAYBEL30 --> WAYBEL_4
  WAYBEL30 --> YELLOW_6
  WAYBEL30 --> YELLOW_8
  WAYBEL30 --> WAYBEL10
  WAYBEL30 --> WAYBEL_6
  WAYBEL30 --> WAYBEL_8
  WAYBEL30 --> WAYBEL12
  WAYBEL30 --> WAYBEL_9
  WAYBEL30 --> WAYBEL11
  WAYBEL30 --> YELLOW_9
  WAYBEL30 --> YELLOW12
  WAYBEL30 --> WAYBEL14
  WAYBEL30 --> YELLOW13
  WAYBEL30 --> WAYBEL19
  WAYBEL30 --> WAYBEL21
  WAYBEL30 --> WAYBEL29
  WAYBEL31 --> YELLOW_0
  WAYBEL31 --> WAYBEL_0
  WAYBEL31 --> YELLOW_1
  WAYBEL31 --> YELLOW_2
  WAYBEL31 --> WAYBEL_1
  WAYBEL31 --> YELLOW_3
  WAYBEL31 --> WAYBEL_2
  WAYBEL31 --> YELLOW11
  WAYBEL31 --> WAYBEL_3
  WAYBEL31 --> WAYBEL_4
  WAYBEL31 --> YELLOW_8
  WAYBEL31 --> WAYBEL_7
  WAYBEL31 --> WAYBEL_8
  WAYBEL31 --> WAYBEL_9
  WAYBEL31 --> WAYBEL11
  WAYBEL31 --> WAYBEL13
  WAYBEL31 --> YELLOW_9
  WAYBEL31 --> YELLOW12
  WAYBEL31 --> WAYBEL14
  WAYBEL31 --> WAYBEL19
  WAYBEL31 --> WAYBEL23
  WAYBEL31 --> YELLOW15
  WAYBEL31 --> WAYBEL25
  WAYBEL31 --> WAYBEL30
  WAYBEL33 --> YELLOW_0
  WAYBEL33 --> WAYBEL_0
  WAYBEL33 --> YELLOW_1
  WAYBEL33 --> YELLOW_2
  WAYBEL33 --> WAYBEL_1
  WAYBEL33 --> YELLOW_4
  WAYBEL33 --> WAYBEL_2
  WAYBEL33 --> WAYBEL_3
  WAYBEL33 --> YELLOW_6
  WAYBEL33 --> WAYBEL_7
  WAYBEL33 --> WAYBEL_8
  WAYBEL33 --> WAYBEL12
  WAYBEL33 --> WAYBEL_9
  WAYBEL33 --> WAYBEL11
  WAYBEL33 --> YELLOW_9
  WAYBEL33 --> YELLOW13
  WAYBEL33 --> WAYBEL19
  WAYBEL33 --> WAYBEL21
  WAYBEL33 --> WAYBEL23
  WAYBEL33 --> WAYBEL28
  WAYBEL33 --> WAYBEL29
  WAYBEL33 --> WAYBEL32
  WAYBEL33 --> YELLOW19
  classDef yellow fill:#fff3bf,stroke:#f08c00,color:#000
  classDef waybel fill:#d0ebff,stroke:#1971c2,color:#000
